services:
  app:
    image: node:lts
    ports:
      - 4321:4321
    working_dir: /app
    command: sh -c "corepack enable && corepack pnpm install --frozen-lockfile && corepack pnpm dev --host 0.0.0.0"
    volumes:
      - ./:/app
      - /app/node_modules
